name: Trigger page update

on:
  push:
    branches:
      - 'main'

concurrency:
  group: "trigger-page-update"
  cancel-in-progress: true

jobs:
  build:
    uses: chilippso/chilippso.github.io/.github/workflows/update.yml@main
